name: Build branch

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - "**"
    tags-ignore:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: windows
            goarch: amd64
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      COMMIT_HASH_test: ${GITHUB_SHA:0:7}
      OUTPUT_test: "mcvisor_${GITHUB_SHA:0:7}_${{ matrix.goos }}_${{ matrix.goarch }}$(go env GOEXE)"
    steps:
      - name: Fetch commit hash
        id: vars
        run: |
          echo ::set-output name=COMMIT_HASH::${GITHUB_SHA:0:7}

      - name: Check out sources
        uses: actions/checkout@v2

      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.18"

      - name: Build
        env:
          OUTPUT: "mcvisor_${{ steps.vars.outputs.COMMIT_HASH }}_${{ matrix.goos }}_${{ matrix.goarch }}$(go env GOEXE)"
        run: |
          printenv | grep test
          go build -v -o "$OUTPUT" ./cmd/mcvisor
          sha512sum "$OUTPUT" > "${OUTPUT}.sha512"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: mcvisor ${{ steps.vars.outputs.COMMIT_HASH }}
          path: "./mcvisor*"
